services:
  - type: worker  # именно worker, а не web
    name: vibeshop-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false