services:
  - type: worker  # вместо web - не требует открытого порта
    name: vibeshop-bot
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: BOT_TOKEN
        sync: false